on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_page:
    name: Build page
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v5
      with:
        node-version: 'latest'
    - name: Install
      run: npm install
    - name: Build
      run: |
        npm run oncescss
        npm run once
